# Generated by Django 3.2.7 on 2021-10-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='core.Profile', verbose_name='автор объявления'),
        ),
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_category', to='core.Post', verbose_name='объявления пользователя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='core.category', verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='core.post', verbose_name='объявления пользователя'),
        ),
    ]
