# Generated by Django 3.2.8 on 2021-10-27 06:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211006_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path, verbose_name='фотография товара'),
        ),
    ]
