# Generated by Django 3.2.8 on 2021-10-27 07:04

import core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[core.validators.validate_date_edit], verbose_name='дата изменения'),
        ),
    ]
