# Generated by Django 3.2.8 on 2021-10-27 07:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_date_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_foto_path, verbose_name='фото пользователя'),
        ),
    ]
