# Generated by Django 3.2.7 on 2021-10-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211001_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
