# Generated by Django 3.2.8 on 2021-10-27 07:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[core.validators.validate_date_edit], verbose_name='день рождения'),
        ),
    ]
