# Generated by Django 3.2.7 on 2021-10-01 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
