# Generated by Django 3.2.7 on 2021-10-01 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_post_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
