# Generated by Django 3.2.8 on 2021-10-27 07:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[core.validators.validate_birth_date], verbose_name='день рождения'),
        ),
    ]
