# Generated by Django 3.2.8 on 2021-10-29 04:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, validators=[core.validators.validate_date_edit], verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
