# Generated by Django 3.2.7 on 2021-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211001_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_post',
            field=models.ManyToManyField(to='core.Post'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_user',
            field=models.ManyToManyField(to='core.Profile'),
        ),
    ]
