# Generated by Django 3.2.7 on 2021-10-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211001_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_post',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_user',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category'),
        ),
    ]
