# Generated by Django 3.2.7 on 2021-10-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211001_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
