# Generated by Django 3.2.7 on 2021-10-01 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211001_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
